export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'

export const MERCHANT_LOGIN_REQUEST = 'MERCHANT_LOGIN_REQUEST'
export const MERCHANT_LOGIN_SUCCESS = 'MERCHANT_LOGIN_SUCCESS'
export const MERCHANT_LOGIN_FAIL = 'MERCHANT_LOGIN_FAIL'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'

export const GET_ALL_OFFICERS_REQUEST = 'GET_ALL_OFFICERS_REQUEST'
export const GET_ALL_OFFICERS_SUCCESS = 'GET_ALL_OFFICERS_SUCCESS'
export const GET_ALL_OFFICERS_FAIL = 'GET_ALL_OFFICERS_FAIL'

export const ADD_OFFICER_REQUEST = 'ADD_OFFICER_REQUEST'
export const ADD_OFFICER_SUCCESS = 'ADD_OFFICER_SUCCESS'
export const ADD_OFFICER_FAIL = 'ADD_OFFICER_FAIL'

export const GET_ONE_OFFICER_REQUEST = 'GET_ONE_OFFICER_REQUEST'
export const GET_ONE_OFFICER_SUCCESS = 'GET_ONE_OFFICER_SUCCESS'
export const GET_ONE_OFFICER_FAIL = 'GET_ONE_OFFICER_FAIL'

export const UPDATE_OFFICER_REQUEST = 'UPDATE_OFFICER_REQUEST'
export const UPDATE_OFFICER_SUCCESS = 'UPDATE_OFFICER_SUCCESS'
export const UPDATE_OFFICER_FAIL = 'UPDATE_OFFICER_FAIL'

export const DELETE_OFFICER_REQUEST = 'DELETE_OFFICER_REQUEST'
export const DELETE_OFFICER_FAIL = 'DELETE_OFFICER_FAIL'

export const UPDATE_ACTIVE_OFFICER_REQUEST = 'UPDATE_ACTIVE_OFFICER_REQUEST'
export const UPDATE_ACTIVE_OFFICER_SUCCESS = 'UPDATE_ACTIVE_OFFICER_SUCCESS'
export const UPDATE_ACTIVE_OFFICER_FAIL = 'UPDATE_ACTIVE_OFFICER_FAIL'

export const GET_ALL_MERCHANT_REQUEST = 'GET_ALL_MERCHANT_REQUEST'
export const GET_ALL_MERCHANT_SUCCESS = 'GET_ALL_MERCHANT_SUCCESS'
export const GET_ALL_MERCHANT_FAIL = 'GET_ALL_MERCHANT_FAIL'

export const ADD_MERCHANT_REQUEST = 'GET_ALL_MERCHANT_REQUEST'
export const ADD_MERCHANT_SUCCESS = 'GET_ALL_MERCHANT_SUCCESS'
export const ADD_MERCHANT_FAIL = 'GET_ALL_MERCHANT_FAIL'

export const GET_ONE_MERCHANT_REQUEST = 'GET_ONE_MERCHANT_REQUEST'
export const GET_ONE_MERCHANT_SUCCESS = 'GET_ONE_MERCHANT_SUCCESS'
export const GET_ONE_MERCHANT_FAIL = 'GET_ONE_MERCHANT_FAIL'

export const UPDATE_MERCHANT_REQUEST = 'UPDATE_MERCHANT_REQUEST'
export const UPDATE_MERCHANT_SUCCESS = 'UPDATE_MERCHANT_SUCCESS'
export const UPDATE_MERCHANT_FAIL = 'UPDATE_MERCHANT_FAIL'

export const DELETE_MERCHANT_REQUEST = 'DELETE_MERCHANT_REQUEST'
export const DELETE_MERCHANT_FAIL = 'DELETE_MERCHANT_FAIL'

export const GET_TOTAL_MERCHANT_REQUEST = 'GET_TOTAL_MERCHANT_REQUEST'
export const GET_TOTAL_MERCHANT_SUCCESS = 'GET_TOTAL_MERCHANT_SUCCESS'
export const GET_TOTAL_MERCHANT_FAIL = 'GET_TOTAL_MERCHANT_FAIL'

export const UPDATE_ACTIVE_REQUEST = 'UPDATE_ACTIVE_REQUEST'
export const UPDATE_ACTIVE_SUCCESS = 'UPDATE_ACTIVE_SUCCESS'
export const UPDATE_ACTIVE_FAIL = 'UPDATE_ACTIVE_FAIL'

export const GET_TRUCK_REQUEST = 'GET_TRUCK_REQUEST'
export const GET_TRUCK_SUCCESS = 'GET_TRUCK_SUCCESS'
export const GET_TRUCK_FAIL = 'GET_TRUCK_FAIL'

export const ADD_TRUCK_REQUEST = 'ADD_TRUCK_REQUEST'
export const ADD_TRUCK_FAIL = 'ADD_TRUCK_FAIL'

export const GET_TRUCK_BYID_REQUEST = 'GET_TRUCK_BYID_REQUEST'
export const GET_TRUCK_BYID_SUCCESS = 'GET_TRUCK_BYID_SUCCESS'
export const GET_TRUCK_BYID_FAIL = 'GET_TRUCK_BYID_FAIL'

export const UPDATE_TRUCK_REQUEST = 'UPDATE_TRUCK_REQUEST'
export const UPDATE_TRUCK_SUCCESS = 'UPDATE_TRUCK_SUCCESS'
export const UPDATE_TRUCK_FAIL = 'UPDATE_TRUCK_FAIL'

export const DELETE_TRUCK_REQUEST = 'DELETE_TRUCK_REQUEST'
export const DELETE_TRUCK_FAIL = 'DELETE_TRUCK_FAIL'

export const GET_TOTAL_COUNT_REQUEST = 'GET_TOTAL_COUNT_REQUEST'
export const GET_TOTAL_COUNT_SUCCESS = 'GET_TOTAL_COUNT_SUCCESS'
export const GET_TOTAL_COUNT_FAIL = 'GET_TOTAL_COUNT_FAIL'

export const ADD_REQUEST = 'ADD_REQUEST'
export const ADD_REQ_SUCCESS = 'ADD_REQ_SUCCESS'
export const ADD_REQ_FAIL = 'ADD_REQ_FAIL'

export const EDIT_REQUEST = 'EDIT_REQUEST'
export const EDIT_REQ_SUCCESS = 'EDIT_REQ_SUCCESS'
export const EDIT_REQ_FAIL = 'EDIT_REQ_FAIL'

export const GET_ALL_MERCHANT_REQ_REQUEST = 'GET_ALL_MERCHANT_REQ_REQUEST'
export const GET_ALL_MERCHANT_REQ_SUCCESS = 'GET_ALL_MERCHANT_REQ_SUCCESS'
export const GET_ALL_MERCHANT_REQ_FAIL = 'GET_ALL_MERCHANT_REQ_FAIL'

export const GET_ALL_REQUESTS = 'GET_ALL_REQUESTS'
export const GET_ALL_REQUESTS_SUCCESS = 'GET_ALL_REQUESTS_SUCCESS'
export const GET_ALL_REQUESTS_FAIL = 'GET_ALL_REQUESTS_FAIL'

export const ADD_HOLIDAY_DATE_REQUESTS = 'ADD_HOLIDAY_DATE_REQUESTS'
export const ADD_HOLIDAY_DATE_SUCCESS = 'ADD_HOLIDAY_DATE_SUCCESS'
export const ADD_HOLIDAY_DATE_FAIL = 'ADD_HOLIDAY_DATE_FAIL'

export const GET_HOLIDAY_DATE_REQUESTS = 'GET_HOLIDAY_DATE_REQUESTS'
export const GET_HOLIDAY_DATE_SUCCESS = 'GET_HOLIDAY_DATE_SUCCESS'
export const GET_HOLIDAY_DATE_FAIL = 'GET_HOLIDAY_DATE_FAIL'

export const DELETE_HOLIDAY_DATE_REQUEST = 'DELETE_HOLIDAY_DATE_REQUEST'
export const DELETE_HOLIDAY_DATE_SUCCESS = 'DELETE_HOLIDAY_DATE_SUCCESS'
export const DELETE_HOLIDAY_DATE_FAIL = 'DELETE_HOLIDAY_DATE_FAIL'

export const ADD_BANKS_REQUESTS = 'ADD_BANKS_REQUESTS'
export const ADD_BANKS_FAIL = 'ADD_BANKS_FAIL'

export const GET_BANKS_REQUESTS = 'GET_BANKS_REQUESTS'
export const GET_BANKS_SUCCESS = 'GET_BANKS_SUCCESS'
export const GET_BANKS_FAIL = 'GET_BANKS_FAIL'

export const DELETE_BANKS_REQUESTS = 'DELETE_BANKS_REQUESTS'
export const DELETE_BANKS_FAIL = 'DELETE_BANKS_FAIL'

export const GET_SINGLE_REQ_REQUESTS = 'GET_SINGLE_REQ_REQUESTS'
export const GET_SINGLE_REQ_SUCCESS = 'GET_SINGLE_REQ_SUCCESS'
export const GET_SINGLE_REQ_FAIL = 'GET_SINGLE_REQ_FAIL'

export const GET_USER_BY_TRUCK_REQUEST = 'GET_USER_BY_TRUCK_REQUEST'
export const GET_USER_BY_TRUCK_SUCCESS = 'GET_USER_BY_TRUCK_SUCCESS'
export const GET_USER_BY_TRUCK_FAIL = 'GET_USER_BY_TRUCK_FAIL'

export const GET_ALL_ROUTE_REQUEST = "GET_ALL_ROUTE_REQUEST";
export const GET_ALL_ROUTE_SUCCESS = "GET_ALL_ROUTE_SUCCESS";
export const GET_ALL_ROUTE_FAIL = "GET_ALL_ROUTE_FAIL";

export const ADD_ROUTE_REQUEST = "ADD_ROUTE_REQUEST";
export const ADD_ROUTE_SUCCESS = "ADD_ROUTE_SUCCESS";
export const ADD_ROUTE_FAIL = "ADD_ROUTE_FAIL";

export const DELETE_ROUTE_REQUEST = "DELETE_ROUTE_REQUEST";
export const DELETE_ROUTE_FAIL = "DELETE_ROUTE_FAIL";

export const UPDATE_ROUTE_REQUEST = "UPDATE_ROUTE_REQUEST";
export const UPDATE_ROUTE_SUCCESS = "UPDATE_ROUTE_SUCCESS";
export const UPDATE_ROUTE_FAIL = "UPDATE_ROUTE_FAIL";

export const GET_ONE_ROUTE_REQUEST = "GET_ONE_ROUTE_REQUEST";
export const GET_ONE_ROUTE_SUCCESS = "GET_ONE_ROUTE_SUCCESS";
export const GET_ONE_ROUTE_FAIL = "GET_ONE_ROUTE_FAIL";

export const UPDATE_MERCHANT_PROFILE_REQUEST = 'UPDATE_MERCHANT_PROFILE_REQUEST'
export const UPDATE_MERCHANT_PROFILE_SUCCESS = 'UPDATE_MERCHANT_PROFILE_SUCCESS'
export const UPDATE_MERCHANT_PROFILE_FAIL = 'UPDATE_MERCHANT_PROFILE_FAIL'

//  for change truck
export const ASSIGN_TRUCK_REQUEST = "ASSIGN_TRUCK_REQUEST";
export const ASSIGN_TRUCK_FAIL = "ASSIGN_TRUCK_FAIL";

// for assign truck
export const ASSIGNED_TRUCK_REQUEST = "ASSIGNED_TRUCK_REQUEST";
export const ASSIGNED_TRUCK_FAIL = "ASSIGNED_TRUCK_FAIL";


export const GET_RECENT_ASSIGN_TRUCKS_REQUEST = "GET_RECENT_ASSIGN_TRUCKS_REQUEST";
export const GET_RECENT_ASSIGN_TRUCKS_SUCCESS = "GET_RECENT_ASSIGN_TRUCKS_SUCCESS";
export const GET_RECENT_ASSIGN_TRUCKS_FAIL = "GET_RECENT_ASSIGN_TRUCKS_FAIL";

export const GET_TOTAL_REQ_COUNT_REQUEST = "GET_TOTAL_REQ_COUNT_REQUEST";
export const GET_TOTAL_REQ_COUNT_SUCCESS = "GET_TOTAL_REQ_COUNT_SUCCESS";
export const GET_TOTAL_REQ_COUNT_FAIL = "GET_TOTAL_REQ_COUNT_FAIL";

export const GET_ASSIGNED_REQ_COUNT_REQUEST = "GET_ASSIGNED_REQ_COUNT_REQUEST";
export const GET_ASSIGNED_REQ_COUNT_SUCCESS = "GET_ASSIGNED_REQ_COUNT_SUCCESS";
export const GET_ASSIGNED_REQ_COUNT_FAIL = "GET_ASSIGNED_REQ_COUNT_FAIL";

export const GET_TRANSIT_REQUEST = "GET_TRANSIT_REQUEST";
export const GET_TRANSIT_SUCCESS = "GET_TRANSIT_SUCCESS";
export const GET_TRANSIT_FAIL = "GET_TRANSIT_FAIL";

export const GET_TYPE_WISE_REQ_REQUEST = "GET_TYPE_WISE_REQ_REQUEST";
export const GET_TYPE_WISE_REQ_SUCCESS = "GET_TYPE_WISE_REQ_SUCCESS";
export const GET_TYPE_WISE_REQ_FAIL = "GET_TYPE_WISE_REQ_FAIL";

export const GET_RECENT_REQ_REQUESTS = "GET_RECENT_REQ_REQUESTS";
export const GET_RECENT_REQ_SUCCESS = "GET_RECENT_REQ_SUCCESS";
export const GET_RECENT_REQ_FAIL = "GET_RECENT_REQ_FAIL";

export const GET_RECENT_REQ_PER_MERCHANT_REQUESTS = "GET_RECENT_REQ_PER_MERCHANT_REQUESTS";
export const GET_RECENT_REQ_PER_MERCHANT_SUCCESS = "GET_RECENT_REQ_PER_MERCHANT_SUCCESS";
export const GET_RECENT_REQ_PER_MERCHANT_FAIL = "GET_RECENT_REQ_PER_MERCHANT_FAIL";

export const GET_TOTAL_MERCHANT_COUNT_REQUEST = 'GET_TOTAL_MERCHANT_COUNT_REQUEST';
export const GET_TOTAL_MERCHANT_COUNT_SUCCESS = 'GET_TOTAL_MERCHANT_COUNT_SUCCESS';
export const GET_TOTAL_MERCHANT_COUNT_FAIL = 'GET_TOTAL_MERCHANT_COUNT_FAIL';

export const UPDATE_USER_ACTIVE_REQUEST = "UPDATE_USER_ACTIVE_REQUEST";
export const UPDATE_USER_ACTIVE_FAIL = "UPDATE_USER_ACTIVE_FAIL";

export const GET_BANK_BYID_REQUESTS = "GET_BANK_BYID_REQUESTS";
export const GET_BANK_BYID_SUCCESS = "GET_BANK_BYID_SUCCESS";
export const GET_BANK_BYID_FAIL = "GET_BANK_BYID_FAIL";

export const UPDATE_BANK_REQUESTS = "UPDATE_BANK_REQUESTS";
export const UPDATE_BANK_SUCCESS = "UPDATE_BANK_SUCCESS";
export const UPDATE_BANK_FAIL = "UPDATE_BANK_FAIL";

export const GET_PER_DAY_REQ_REQUEST = "GET_PER_DAY_REQ_REQUEST";
export const GET_PER_DAY_REQ_SUCCESS = "GET_PER_DAY_REQ_SUCCESS";
export const GET_PER_DAY_REQ_FAIL = "GET_PER_DAY_REQ_FAIL";

export const ADD_NOTIFICATION_REQUEST = "ADD_NOTIFICATION_REQUEST";
export const ADD_NOTIFICATION_SUCCESS = "ADD_NOTIFICATION_SUCCESS";
export const ADD_NOTIFICATION_FAIL = "ADD_NOTIFICATION_FAIL";

export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAIL = "GET_NOTIFICATION_FAIL";


export const UPDATE_ADMIN_PROFILE_REQUESTS = "UPDATE_ADMIN_PROFILE_REQUESTS";
export const UPDATE_ADMIN_PROFILE_SUCCESS = "UPDATE_ADMIN_PROFILE_SUCCESS";
export const UPDATE_ADMIN_PROFILE_FAIL = "UPDATE_ADMIN_PROFILE_FAIL";

export const GET_NOTIFICATION_COUNT_REQUEST = "GET_NOTIFICATION_COUNT_REQUEST";
export const GET_NOTIFICATION_COUNT_SUCCESS = "GET_NOTIFICATION_COUNT_SUCCESS";
export const GET_NOTIFICATION_COUNT_FAIL = "GET_NOTIFICATION_COUNT_FAIL";

export const UPDATE_NOTIFICATION_COUNT_REQUEST = "UPDATE_NOTIFICATION_COUNT_REQUEST";
export const UPDATE_NOTIFICATION_COUNT_SUCCESS = "UPDATE_NOTIFICATION_COUNT_SUCCESS";
export const UPDATE_NOTIFICATION_COUNT_FAIL = "UPDATE_NOTIFICATION_COUNT_FAIL";

export const GET_ROUTE_SUCCESS = "GET_ROUTE_SUCCESS";
export const GET_ROUTE_REQUEST = "GET_ROUTE_REQUEST";
export const GET_ROUTE_FAIL = "GET_ROUTE_FAIL";

export const GET_TRUCK_BY_ZONE_REQUEST = 'GET_TRUCK_BY_ZONE_REQUEST';
export const GET_TRUCK_BY_ZONE_SUCCESS = 'GET_TRUCK_BY_ZONE_SUCCESS';
export const GET_TRUCK_BY_ZONE_FAIL = 'GET_TRUCK_BY_ZONE_FAIL';

export const GET_ADMIN_DETAILS_REQ = 'GET_ADMIN_DETAILS_REQ';
export const GET_ADMIN_DETAILS_SUCCESS = 'GET_ADMIN_DETAILS_SUCCESS';
export const GET_ADMIN_DETAILS_FAIL = 'GET_ADMIN_DETAILS_FAIL';